"""empty message

Revision ID: 1a216457a615
Revises: 9a9256bd4f48
Create Date: 2021-04-07 10:41:10.789161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a216457a615'
down_revision = '9a9256bd4f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('date_modified', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('userhash', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'userhash')
    op.drop_column('user', 'date_modified')
    op.drop_column('user', 'date_created')
    # ### end Alembic commands ###
