"""empty message

Revision ID: 39db843b5364
Revises: 9ceb1ba0bfd1
Create Date: 2021-05-12 13:13:44.666183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39db843b5364'
down_revision = '9ceb1ba0bfd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_comments', 'date_modified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_comments', sa.Column('date_modified', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
