"""empty message

Revision ID: 769b74334c8a
Revises: 19f8622ee87b
Create Date: 2021-05-04 20:06:54.346842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769b74334c8a'
down_revision = '19f8622ee87b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filetype', sa.String(length=50), nullable=True),
    sa.Column('filename', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('date_limit', sa.DateTime(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_task_attemps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=4000), nullable=True),
    sa.Column('attachment', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attachment'], ['user_file.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['course_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('date_limit', sa.DATETIME(), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('date_modified', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('course_task_attemps')
    op.drop_table('course_tasks')
    op.drop_table('user_file')
    # ### end Alembic commands ###
