"""empty message

Revision ID: e68c8786f54c
Revises: 769b74334c8a
Create Date: 2021-05-06 20:06:55.575105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68c8786f54c'
down_revision = '769b74334c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_file', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_file', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_file', type_='foreignkey')
    op.drop_column('user_file', 'user_id')
    # ### end Alembic commands ###
